version: '3'

services:
  api:
    build:
      context: .
      dockerfile: docker/api_dockerfile
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on: 
      - redis
      - worker
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379    
    networks:
      - backend

  gui:
    build:
      context: .
      dockerfile: docker/gui_dockerfile
    depends_on: 
      - api
    ports:
      - "8080:80"
    restart: unless-stopped 
    networks:
      - backend
 
  worker:
    build:
      context: .
      dockerfile: docker/api_dockerfile
    hostname: worker
    entrypoint: celery
    command: -A recipes worker --loglevel=INFO
    environment:
      CACHE_REDIS_HOST: "redis"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      API_HOST: api
    volumes:
      - ./backend:/app
    links:
      - redis
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: "redis:alpine"
    restart: unless-stopped
    networks:
      - backend

networks:
  backend: