version: "3"

services:
  api:
    build:
      context: .
      dockerfile: docker/api_dockerfile
    ports:
      - "8081:8081"
    restart: unless-stopped
    # Uncomment the following lines if running against actual hardware
    #      HARDWARE_PACKAGE: real
    #    devices:
    #      -  /dev/gpiomem:/dev/gpiomem
    #      -  /dev/ttyUSB0:/dev/ttyUSB0
    #      -  /dev/ttyUSB1:/dev/ttyUSB1
    #      -  /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - ./docker/microlab-docker.ini:/etc/microlab/microlab.ini
      - ./backend:/app
      - ./docker/data:/var/lib/microlab
      
    networks:
      - backend

  gui:
    build:
      context: .
      dockerfile: docker/gui_dockerfile
    depends_on:
      - api
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
